[package]
name = "timelapse_lego"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25.8", features = ["avif"] }
ffmpeg-next = "8.0.0"
clap = { version = "4.5.49", features = ["derive"] }